title: Solar Halo Studio
description: Indie Game Developer
show_downloads: false
show_github: false
my_name: Jim Cheng
post_images: post_images
title_images: title_images
excerpt_separator: <!--more-->
url: https://www.solarhalostudio.com

paginate: 5
paginate_path: "/blog/page:num/"
